language: java
sudo: false
jdk:
  - oraclejdk8
install: true

before_script:
  - mvn install:install-file -Dfile=$TRAVIS_BUILD_DIR/libs/java-crypto-conditions-2.0.0-SNAPSHOT.jar -DgroupId=org.interledger -DartifactId=java-crypto-conditions -Dversion=2.0.0-SNAPSHOT -Dpackaging=jar

branches:
  only:
  - AssetAndMetaData-as-Obj-Issue-36

script:
  - mvn clean install
